name: surviveoffline
description: Offline reader with non-intrusive ads
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  google_mobile_ads: ^5.1.0
  path_provider: ^2.1.4
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  markdown: ^7.2.2
  url_launcher: ^6.3.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/srv.off.png"
  adaptive_icon_foreground: "assets/srv.off.png"
  adaptive_icon_background: "#F0EBDD"

flutter:
  uses-material-design: true
  assets:
    - assets/sample_content.json
    - assets/srv.off.png
